server:
  port: 8080
spring:
  application:
    name: movie-reservation
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
